import React from 'react';
import {
  Gauge,
  Droplet,
  PenLine,
  Hotel,
  CalendarCheck,
  KeyRound,
  Sparkles,
  UtensilsCrossed,
  Receipt,
  Puzzle,
  MousePointerClick,
  PieChart,
  FileEdit,
  Star,
  Bell,
  Calculator,
  FileStack,
  FileText,
} from 'lucide-react';

export const navItems = [
  {
    type: 'item',
    name: 'Dashboard',
    id: 'dashboard',
    icon: Gauge,
    badge: { color: 'info', text: 'NEW' },
  },
  {
    type: 'title',
    name: 'THEME',
  },
  {
    type: 'item',
    name: 'Colors',
    id: 'theme-colors',
    icon: Droplet,
  },
  {
    type: 'item',
    name: 'Typography',
    id: 'theme-typography',
    icon: PenLine,
  },
  {
    type: 'title',
    name: 'HOTEL MANAGEMENT',
  },
  {
    type: 'item',
    name: 'Sơ Đồ Phòng',
    id: 'rooms',
    icon: Hotel,
  },
  {
    type: 'item',
    name: 'Đặt Phòng',
    id: 'bookings',
    icon: CalendarCheck,
  },
  {
    type: 'item',
    name: 'Check-in / Check-out',
    id: 'checkin',
    icon: KeyRound,
  },
  {
    type: 'item',
    name: 'Buồng Phòng',
    id: 'housekeeping',
    icon: Sparkles,
  },
  {
    type: 'item',
    name: 'Order Dịch Vụ',
    id: 'services',
    icon: UtensilsCrossed,
  },
  {
    type: 'item',
    name: 'Hóa Đơn & Báo Cáo',
    id: 'invoices',
    icon: Receipt,
  },
  {
    type: 'title',
    name: 'COMPONENTS',
  },
  {
    type: 'group',
    name: 'Base',
    id: 'base',
    icon: Puzzle,
    items: [
      { name: 'Accordion', id: 'base-accordion' },
      { name: 'Breadcrumbs', id: 'base-breadcrumbs' },
      { name: 'Cards', id: 'base-cards' },
      { name: 'Carousels', id: 'base-carousels' },
      { name: 'Collapse', id: 'base-collapse' },
      { name: 'Navs & Tabs', id: 'base-navs' },
      { name: 'Pagination', id: 'base-pagination' },
      { name: 'Progress', id: 'base-progress' },
      { name: 'Tables', id: 'base-tables' },
    ],
  },
  {
    type: 'group',
    name: 'Buttons',
    id: 'buttons',
    icon: MousePointerClick,
    items: [
      { name: 'Buttons', id: 'btn-buttons' },
      { name: 'Button Groups', id: 'btn-groups' },
      { name: 'Dropdowns', id: 'btn-dropdowns' },
    ],
  },
  {
    type: 'item',
    name: 'Charts',
    id: 'charts',
    icon: PieChart,
  },
  {
    type: 'group',
    name: 'Forms',
    id: 'forms',
    icon: FileEdit,
    items: [
      { name: 'Form Control', id: 'form-control' },
      { name: 'Select', id: 'form-select' },
      { name: 'Checks & Radios', id: 'form-checks' },
      { name: 'Range', id: 'form-range' },
    ],
  },
  {
    type: 'group',
    name: 'Icons',
    id: 'icons',
    icon: Star,
    items: [
      { name: 'CoreUI Icons', id: 'icons-coreui' },
      { name: 'Flags', id: 'icons-flags' },
      { name: 'Brands', id: 'icons-brands' },
    ],
  },
  {
    type: 'group',
    name: 'Notifications',
    id: 'notifications',
    icon: Bell,
    items: [
      { name: 'Alerts', id: 'notif-alerts' },
      { name: 'Badges', id: 'notif-badges' },
      { name: 'Modals', id: 'notif-modals' },
      { name: 'Toasts', id: 'notif-toasts' },
    ],
  },
  {
    type: 'item',
    name: 'Widgets',
    id: 'widgets',
    icon: Calculator,
    badge: { color: 'info', text: 'NEW' },
  },
  {
    type: 'title',
    name: 'EXTRAS',
  },
  {
    type: 'group',
    name: 'Pages',
    id: 'pages',
    icon: FileStack,
    items: [
      { name: 'Login', id: 'page-login' },
      { name: 'Register', id: 'page-register' },
      { name: 'Error 404', id: 'page-404' },
      { name: 'Error 500', id: 'page-500' },
    ],
  },
  {
    type: 'item',
    name: 'Docs',
    id: 'docs',
    icon: FileText,
  },
];
